### ISSUE TITLE
onnodig commentaar

### ISSUE THREAD

**Issue by NitraatPlagiaat** [NitraatPlagiaat/magnick#3]
maggy, je hebt kutcode.

**Comment by Requentes** [comment]
kut yirnick hou je bek gvd

**Comment by NitraatPlagiaat** [comment]
commit die

**Comment by Requentes** [comment]
DELETE FROM yirnick WHERE condition = corona;

**Comment by NitraatPlagiaat** [comment]
nu moet ik poepen

**Comment by Requentes** [comment]
Ga maar naar Jeroen Elswijk

**Comment by NitraatPlagiaat** [comment]
zijn adres is Gouden Leeuw 146 1103 KC Amsterdam. of bel hem op 06-21225197

**Comment by Requentes** [comment]
gvd kut yirnick

**Comment by Requentes** [comment]
$("#stop").click(function(){
  $("#yirnick").stop();
});

**Comment by NitraatPlagiaat** [comment]
ik heb nu stront in me haar

**Comment by Requentes** [comment]
ja vind je wel geil he
![meme](https://user-images.githubusercontent.com/71263806/93088139-d60fa480-f699-11ea-9a49-a8f7ec134ef5.png)
