### ISSUE TITLE
yirnick

### ISSUE THREAD

**Issue by Requentes** [NitraatPlagiaat/magnick#4]
wil je even valid commentaar achterlaten dankjewel
![r_1973724_9QTSY](https://user-images.githubusercontent.com/71263806/93096363-94d0c200-f6a4-11ea-8d6c-b6cac72072fc.jpg)

**Comment by NitraatPlagiaat** [comment]
me

**Comment by Requentes** [comment]
ok

**Comment by Requentes** [comment]
![image](https://user-images.githubusercontent.com/71263806/93189787-dca62680-f742-11ea-8859-a773d5a4364a.png)

yeet
